### ISSUE TITLE
Week 3 Homework

### ISSUE THREAD

**Issue by Kenneffy** [JasonMartocci/Hangman#1]
GREAT music and aesthetic, I love the layout. Game functions well and code it organized in a very understandable way. Showing good readability in code, a skill that is very desired in team collaboration. Feel free to delete any code that is not needed. You don't want to come back to the code later and mistaken it as a part of application. :)

**Comment by JasonMartocci** [comment]
I am still going to work on it some more and try to make a mobile version so I just finished what I could. 

Thank you for the feedback.
